menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'Blog', url: '/blog'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Maliha Aziz', title: 'Research Scientist', department: 'Antibiotic Resistance Action Center', institution: 'George Washington University', institution_address: 'Washington, DC', phone: '(480) 735-1085', email: 'aziz.maliha@gmail.com', office: '', image: 'assets/img/maliha-aziz.jpg', url: 'maliha-aziz'}

courses:
- {name: 'Machine Learning I: Algorithm Analysis', url: 'machine-learning-i'}
- {name: 'Machine Learning II: Data Analysis', url: 'machine-learning-ii'}
- {name: 'Bioinformatics', url: 'bioinformatics'}
- {name: 'Computational Biology', url: 'computational-biology'}

social:
- {icon: 'github', link: 'https://github.com/malihaaziz'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/malihaaziz'}

contacts:
- {name: 'Maliha Aziz', title: 'Research Scientist', department: 'Antibiotic Resistance Action Center', institution: 'George Washington University', institution_address: 'Washington, DC', phone: '(480) 735-1085', email: 'aziz.maliha@gmail.com', office: '', image: 'assets/img/maliha-aziz.jpg'}
